"""SKILL.md rendering.

Kept short on purpose. The spec budget is 500 lines and ~5000 tokens for the body, and
the detail a reader occasionally needs (full binding table, stand-in caveats, gate
list) lives one level down in `references/`. What stays here is what a reader needs
before doing anything: what this skill assumes, what it will do, and where it will stop.
"""

from .. import config

BINDING_ORDER = ("native", "mcp", "script", "ask-user", "drop")


def _describe(inventory, profile, summary):
    source = inventory.get("source") or {}
    where = source.get("url") or "a local repository"
    total = summary["operations"]
    return (
        f"Operate {where} through its {total} extracted operations, each resolved "
        f"against the {profile.name} harness profile. Use when a task maps to this "
        f"repository's pipeline and you need to know which steps this harness can "
        f"actually perform, which are degraded to declared stand-ins, and which must "
        f"stop for a human. States its capability assumptions explicitly rather than "
        f"assuming tools exist."
    )[: config.DESCRIPTION_MAX_CHARS]


def _compatibility(inventory, profile):
    source = inventory.get("source") or {}
    bits = [f"Requires the {profile.name} profile ({profile.id})"]
    if source.get("sha"):
        bits.append(f"resolved against {source['sha']}")
    bits.append(f"generated by repo-to-skill {config.CONVERTER_VERSION}")
    return "; ".join(bits)[: config.COMPATIBILITY_MAX_CHARS]


def _frontmatter(name, inventory, profile, summary):
    source = inventory.get("source") or {}
    lines = [
        "---",
        f"name: {name}",
        f"description: {_describe(inventory, profile, summary)}",
        "license: MIT",
        f"compatibility: {_compatibility(inventory, profile)}",
        "metadata:",
        f"  repo_class: {inventory.get('repo_class', 'unknown')}",
        f"  profile: {profile.id}",
        f"  inventory_status: {inventory.get('inventory_status', 'unknown')}",
        f"  converter_version: {config.CONVERTER_VERSION}",
    ]
    if source.get("url"):
        lines.append(f"  source: {source['url']}")
    if source.get("sha"):
        lines.append(f"  source_sha: {source['sha']}")
    lines.append("---")
    return "\n".join(lines)


def _profile_block(profile, summary, rows):
    """The first thing in the body. Non-negotiable: see the module docstring."""
    native = [r for r in rows if r["binding"] == "native"]
    mcp = [r for r in rows if r["binding"] == "mcp"]
    lines = [
        "## Capability profile this skill assumes",
        "",
        f"Resolved for the **{profile.name}** profile (`{profile.id}`).",
        "",
        "| Channel | Count | Meaning |",
        "|---|---|---|",
        f"| native | {len(native)} | the harness performs it directly |",
        f"| mcp | {len(mcp)} | reached through an attached MCP server |",
        f"| script | {summary['bindings']['script']} | degraded to a declared stand-in |",
        f"| ask-user | {summary['bindings']['ask-user']} | stops and asks a human |",
        f"| drop | {summary['bindings']['drop']} | optional, not performed |",
        "",
        f"Coverage index **{summary['coverage']}** "
        f"(heuristic: native 1.0, mcp 0.9, script = declared fidelity, ask-user 0.5, "
        f"drop 0.0).",
        "",
    ]

    if summary["all_required_operations_executable"]:
        lines.append("Every required operation is executable on this harness.")
    else:
        halts = ", ".join(f"`{h}`" for h in summary["halted"]) or "none"
        lines.append(
            f"**This harness cannot complete the pipeline unattended.** It stops for "
            f"human input at: {halts}."
        )

    lines += [
        "",
        "> If your harness is not this profile, these bindings do not hold. Re-run "
        "`r2s convert` against your own profile rather than assuming.",
        "",
    ]
    return lines


def _pipeline_table(rows):
    lines = [
        "## Pipeline",
        "",
        "| # | Operation | Phase | Effect | Binding | Gates | Confidence |",
        "|---|---|---|---|---|---|---|",
    ]
    for index, row in enumerate(sorted(rows, key=lambda r: (r["stage"], r["id"])), start=1):
        gates = ", ".join(row["gates"])
        if not gates and row["deferred_gates"]:
            gates = f"deferred: {', '.join(row['deferred_gates'])}"
        lines.append(
            f"| {index} | `{row['id']}` | {row['stage']} | {row['effect']} | "
            f"{row['binding']} | {gates or '-'} | {row['confidence']} |"
        )
    lines.append("")
    return lines


def _stops_block(summary, rows):
    """What this skill will refuse to do without a human. The honest core of the skill."""
    blocked = [r for r in rows if r["binding"] == "ask-user"]
    degraded = [r for r in rows if r["binding"] == "script" and r["stand_in_detail"]]
    lost = [r for r in rows if r["binding"] == "drop"]

    lines = ["## Where this skill stops", ""]

    if blocked:
        lines.append("**Halts for a human.** These do not run unattended:")
        lines.append("")
        for row in blocked:
            gates = ", ".join(row["deferred_gates"])
            suffix = f" — gates deferred into the question: {gates}" if gates else ""
            lines.append(f"- `{row['id']}`: needs {', '.join(row['missing'])}{suffix}")
        lines.append("")

    if degraded:
        lines.append("**Degraded.** These run, but not as the real thing:")
        lines.append("")
        for row in degraded:
            detail = row["stand_in_detail"]
            lines.append(
                f"- `{row['id']}`: {detail['desc']} (fidelity {detail['fidelity']}, "
                f"stand-in `{row['stand_in']}`)"
            )
        lines.append("")
        lines.append(
            "> A stand-in is not the real thing. Report degraded output as degraded "
            "rather than presenting it as the intended result."
        )
        lines.append("")

    if lost:
        lines.append(
            f"**Not performed.** Optional operations this harness drops: "
            f"{', '.join(f'`{r[chr(105) + chr(100)]}`' for r in lost)}."
        )
        lines.append("")

    if not (blocked or degraded or lost):
        lines.append("Nothing is degraded or blocked on this harness.")
        lines.append("")

    return lines


def _gates_block(rows, summary):
    gated = [r for r in rows if r["gates"]]
    lines = ["## Gates", ""]
    if not gated and not summary["deferred_gates"]:
        lines += ["No operations carry gates on this harness.", ""]
        return lines

    lines += [
        "Gates are fail-closed. A gate is never weakened by a better harness — a "
        "stronger harness buys a better *binding*, not a weaker gate.",
        "",
    ]
    if gated:
        lines += ["| Operation | Gates | Confidence |", "|---|---|---|"]
        for row in sorted(gated, key=lambda r: r["id"]):
            lines.append(
                f"| `{row['id']}` | {', '.join(row['gates'])} | "
                f"{row.get('gate_confidence') or 'n/a'} |"
            )
        lines.append("")
    if summary["deferred_gates"]:
        lines += [
            f"Gates deferred into questions rather than enforced here: "
            f"{', '.join(summary['deferred_gates'])}. See `references/blocked.md`.",
            "",
        ]
    return lines


def _references_block(summary):
    lines = ["## References", ""]
    lines.append("- `references/bindings.md` — the full binding table with evidence")
    if summary["degraded"]:
        lines.append("- `references/degradation.md` — what is degraded, and how much")
    if summary["bindings"]["ask-user"]:
        lines.append("- `references/blocked.md` — the questions to ask, with safe defaults")
    lines.append("- `references/gates.md` — fail-closed gates")
    lines.append("")
    return lines


def _unreviewed_block(inventory, rows, warnings):
    if inventory.get("inventory_status") != "accepted-unreviewed":
        return []
    low = [r for r in rows if r["confidence"] == "low"]
    lines = [
        "## Unreviewed inventory — treat as unconfirmed",
        "",
        "This skill was emitted from an inventory that a human has **not** reviewed. "
        "The operations below are the least certain, and any of them may be wrong.",
        "",
    ]
    if low:
        lines += ["| Operation | Confidence | Requires |", "|---|---|---|"]
        for row in sorted(low, key=lambda r: r["id"]):
            lines.append(f"| `{row['id']}` | {row['confidence']} | {', '.join(row['requires'])} |")
        lines.append("")
    else:
        lines += [
            "No operation is individually low-confidence, but the inventory as a "
            "whole is unconfirmed.",
            "",
        ]
    for warning in warnings:
        lines.append(f"- {warning}")
    lines.append("")
    return lines


def render(inventory, profile, rows, summary, warnings=None):
    """Return (frontmatter, body). The caller joins them with a blank line."""
    warnings = warnings or []
    source = inventory.get("source") or {}
    stem = (source.get("url") or "repository").rstrip("/").removesuffix(".git")
    title = stem.rsplit("/", 1)[-1] or "repository"
    name = _skill_name_from(profile, inventory)

    body = []
    body.append(f"# {title} — capability skill")
    body.append("")
    body.append(
        "Generated from the repository's extracted operations. Every step below is "
        "annotated with how *this* harness will perform it."
    )
    body.append("")
    body.extend(_profile_block(profile, summary, rows))
    body.extend(_unreviewed_block(inventory, rows, warnings))
    body.extend(_pipeline_table(rows))
    body.extend(_stops_block(summary, rows))
    body.extend(_gates_block(rows, summary))
    body.extend(_references_block(summary))

    frontmatter = _frontmatter(name, inventory, profile, summary)
    return frontmatter, "\n".join(body).strip()


def _skill_name_from(profile, inventory):
    from ..util.io import slugify

    source = inventory.get("source") or {}
    url = source.get("url") or ""
    stem = url.rstrip("/").removesuffix(".git").rsplit("/", 1)[-1] if url else "repo"
    base = slugify(f"{stem}-skill")[:40].strip("-") or "repo-skill"
    profile_part = slugify(profile.id)[:16].strip("-")
    name = f"{base}-{profile_part}" if profile_part else base
    return name[: config.NAME_MAX_CHARS].strip("-")
